export default {
	GET_MAIN_DATA: 'GET_MAIN_DATA',
	GET_API_DATA: 'GET_API_DATA',
	UPDATE_SEARCH: 'UPDATE_SEARCH',
	CATEGORY_DETAILS : 'CATEGORY_DETAILS',
	RESET_STATE: 'RESET_STATE',
	UPDATE_STATE: 'UPDATE_STATE',
	PROGRAM_SEARCH: 'PROGRAM_SEARCH',
	RESET_PROGRAMS_STATE: 'RESET_PROGRAMS_STATE'
}